const START_CHARACTERS_LOADING = 'START_CHARACTERS_LOADING';
const END_CHARACTERS_LOADING = 'END_CHARACTERS_LOADING'
const SET_CHARACTERS = 'CHARACTERS'


export {
    START_CHARACTERS_LOADING,
    END_CHARACTERS_LOADING,
    SET_CHARACTERS,
}